# netlify.toml
# Netlify Configuration for Next.js 14 App Router

[build]
  command = "npm run build"

# Automatically uses the Next.js Runtime on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["!node_modules/next/dist/compiled/@next/swc*/**", "!*.zip", "!**/*.zip", "!.next/cache/**"]
  node_bundler = "nft"

[functions."___netlify-server-handler"]
  included_files = ["!node_modules/next/dist/compiled/@next/swc*/**", "!*.zip", "!**/*.zip", "!.next/cache/**"]
